[env:esp32-s3-touch-lcd-5]
platform = https://github.com/tasmota/platform-espressif32/releases/download/2024.10.30/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = default_16MB.csv

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D DISABLE_ALL_LIBRARY_WARNINGS
    -D ESP_PANEL_USE_RGB_INTERFACE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D LV_CONF_INCLUDE_SIMPLE -I include/utils
    -fexceptions
    -I include/Tasks
    -I include/Defines

lib_deps = 
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#master
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#master
    https://github.com/esp-arduino-libs/esp-lib-utils.git#master
    lvgl/lvgl @ ^8.4.0
